language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pyqt5
  - python -c 'import PyQt5.QtCore' &&
      echo 'PyQt5 is available' ||
      echo 'PyQt5 is not available'
  - pip install --quiet .
# command to run tests
script:
  - py.test

